### ISSUE TITLE
Make custom color picker with sliders

### ISSUE THREAD

**Issue by marcin-wosinek** [marcin-wosinek/sticky-notes#20]
Use [slider](https://material.angularjs.org/#/demo/material.components.slider) to set colors of a note.

Looks that the styles need to be set in our custom style.

``` css
/*!
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v0.6.1
 */
md-backdrop.md-opaque.md-red-theme {
  background-color: rgba(0, 0, 0, 0.3);
  position: absolute; }

md-bottom-sheet.md-red-theme {
  background-color: #fafafa;
  border-top-color: #bdbdbd; }
  md-bottom-sheet.md-red-theme.md-list md-item {
    color: rgba(0, 0, 0, 0.54); }
  md-bottom-sheet.md-red-theme .md-subheader {
    background-color: #fafafa; }
  md-bottom-sheet.md-red-theme .md-subheader {
    color: rgba(0, 0, 0, 0.54); }
```
